version: '3.83'
services:
  fe-app:
    image: crpi-966g44lkhzc56vyh.cn-guangzhou.personal.cr.aliyuncs.com/liao_liao/liao:aaa
    ports:
      - 80:80
    depends_on:
      - nest-app
    restart: always
    networks:
      - common-network
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    # ports:
    #   - 3005:3005
    depends_on:
      - mysql-container
      - redis-container
    restart: always
    networks:
      - common-network
  mysql-container:
    image: mysql
    volumes:
      - /Users/leon/mysql-data:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci # 设置默认字符集
    environment:
      MYSQL_DATABASE: meeting_room_booking_system
      MYSQL_ROOT_PASSWORD: leon
    restart: always
    networks:
      - common-network
  redis-container:
    image: redis
    volumes:
      - /Users/leon/redis-data:/data
    restart: always
    networks:
      - common-network
networks:
  common-network:
    driver: bridge
